services: 
  oracledb:
    container_name: oracledb
    build: ./oracle
    networks:
      - boardnet
    ports:
      - 1521:1521  
    restart: always
  spring:
    container_name: spring
    depends_on:
      - oracledb
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracledb:1521/xe
    build: 
      dockerfile: Dockerfile
    networks:
      - boardnet
    restart: always
    ports:
      - 8080:8080
networks:
  boardnet: